name: Gene Kogan
markdown: kramdown
collections:
  book:
    output: true
    permalink: /ml4a/:path/
  translations:
    output: true
    permalink: /ml4a/:path/
  guides:
    output: true
    permalink: /guides/:path/
  demos:
    output: true
    permalink: /demos/:path/
  pages:
    output: true
    permalink: /:path/
